config/routes.rb
Rails.application.routes.draw do

  match '/sensorin',:controller=>'sensorinputs',:action=>'sensorin',via:[:get,:post]
  resources :sensorinputs

end

app/models/sensorinput.rb
class Sensorinput < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sensorinputs_controller.rb
require 'pusher'
class SensorinputsController < ApplicationController
  before_action :set_sensorinput, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :create

  def sensorin
    responseto="OK"
    Pusher.app_id = '185633'
    Pusher.key = '845298bc064d47d6943d'
    Pusher.secret = 'ffc4142d5ee0ee498159'
    Pusher.logger = Rails.logger
    Pusher.encrypted = true
    if params[:q].index("S")!=nil
      Pusher.trigger('test_channel', 'my_event', {
        message: params[:q][1..3]
      })
    end
    if params[:q].index("B")!=nil
      Pusher.trigger('test_channel', 'my_event', {
        beat: params[:q][1..3]
      })  
    end
    
    respond_to do |format|
        format.json { render json: responseto.to_json }
    end
  end
  # GET /sensorinputs
  # GET /sensorinputs.json
  def index
    @sensorinputs = Sensorinput.all
  end

  # GET /sensorinputs/1
  # GET /sensorinputs/1.json
  def show
  end

  # GET /sensorinputs/new
  def new
    @sensorinput = Sensorinput.new
  end

  # GET /sensorinputs/1/edit
  def edit
  end

  # POST /sensorinputs
  # POST /sensorinputs.json
  def create
    @sensorinput = Sensorinput.new(sensorinput_params)

    respond_to do |format|
      if @sensorinput.save
        format.html { redirect_to @sensorinput, notice: 'Sensorinput was successfully created.' }
        format.json { render :show, status: :created, location: @sensorinput }
      else
        format.html { render :new }
        format.json { render json: @sensorinput.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensorinputs/1
  # PATCH/PUT /sensorinputs/1.json
  def update
    respond_to do |format|
      if @sensorinput.update(sensorinput_params)
        format.html { redirect_to @sensorinput, notice: 'Sensorinput was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensorinput }
      else
        format.html { render :edit }
        format.json { render json: @sensorinput.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensorinputs/1
  # DELETE /sensorinputs/1.json
  def destroy
    @sensorinput.destroy
    respond_to do |format|
      format.html { redirect_to sensorinputs_url, notice: 'Sensorinput was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensorinput
      @sensorinput = Sensorinput.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensorinput_params
      params.require(:sensorinput).permit(:raw_info, :data_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensorinputs_helper.rb
module SensorinputsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
            <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/patterns.js"></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<script src="https://js.pusher.com/3.0/pusher.min.js"></script>
<script src="/js/index.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sensorinputs/_form.html.erb
<%= form_for(@sensorinput) do |f| %>
  <% if @sensorinput.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensorinput.errors.count, "error") %> prohibited this sensorinput from being saved:</h2>

      <ul>
      <% @sensorinput.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :raw_info %><br>
    <%= f.number_field :raw_info %>
  </div>
  <div class="field">
    <%= f.label :data_type %><br>
    <%= f.text_field :data_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensorinputs/edit.html.erb
<h1>Editing sensorinput</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensorinput %> |
<%= link_to 'Back', sensorinputs_path %>

app/views/sensorinputs/index.html.erb
<div class="row">
<div class="col-md-1 col-md-offset-1">
<div id="chest">
  <div style="position: relative;
    top: 110px;
    left: 70px;
    z-index: 30;color:#fff">
    <p id="beatmon"> 35 bpm</p>
  </div>
  <div class="heart left side top"></div>
  <div class="heart center">&hearts;</div>
  <div class="heart right side"></div>
</div>
</div>
<div class="col-md-9">
<div class="mapbg">
  <div id="chartdiv"></div>  
</div>
</div>
</div>

app/views/sensorinputs/new.html.erb
<h1>New sensorinput</h1>

<%= render 'form' %>

<%= link_to 'Back', sensorinputs_path %>

app/views/sensorinputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Raw info:</strong>
  <%= @sensorinput.raw_info %>
</p>

<p>
  <strong>Data type:</strong>
  <%= @sensorinput.data_type %>
</p>

<%= link_to 'Edit', edit_sensorinput_path(@sensorinput) %> |
<%= link_to 'Back', sensorinputs_path %>